### ISSUE TITLE
Fix Loading Error when trying to load 8gb file

### ISSUE THREAD

**Issue by 1-alex98** [TPrime001/Gerichtsurteile#1]
Traceback (most recent call last):
  File "C:/Users/USER/PycharmProjects/Gerichtsurteile/index.py", line 10, in <module>
    data_all = json.load(open(filename,"r"))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35-32\lib\json__init__.py", line 265, in load
    return loads(fp.read(),
MemoryError

**Comment by 1-alex98** [comment]
Or make smaller subunits

**Comment by tigger-3** [comment]
done, but i have some new problems...

Traceback (most recent call last):
  File "C:/Users/Sebastian/PycharmProjects/Papenburg/Gerichtsurteile/GUI.py", line 3, in <module>
    from Query import info
  File "C:\Users\Sebastian\PycharmProjects\Papenburg\Gerichtsurteile\Query.py", line 4, in <module>
    from Query_IBSearch import filteroutput, filtershortcuts, info
  File "C:\Users\Sebastian\PycharmProjects\Papenburg\Gerichtsurteile\Query_IBSearch.py", line 11, in <module>
    index = pickle.load(f)
_pickle.UnpicklingError

I will close this bug and open another one.
